name: publish
on:
    workflow_dispatch:
    push:
        branches:
            - publish
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: publish
        steps:
            - uses: actions/checkout@v2
            - run: yarn
            - run: yarn build
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
